apiVersion: v1
kind: Pod
metadata:
    name: sample-pod
    labels:
        env: dev
        vasd: B6NV
spec:
    containers:
    - name: sample-container
      image: tomcat
      ports:
      - containerPort: 8080
