apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: certbot
  name: certbot
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: certbot/certbot
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
