apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: certbot
  name: certbot
spec:
  replicas: 1
  selector:
    io.kompose.service: certbot
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: certbot
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - trap exit TERM; while :; do certbot renew; sleep 12h & wait ${!}; done;
        image: ' '
        name: certbot
        resources: {}
        volumeMounts:
        - mountPath: /etc/letsencrypt
          name: certbot-claim0
        - mountPath: /var/www/certbot
          name: certbot-claim1
      volumes:
      - name: certbot-claim0
        persistentVolumeClaim:
          claimName: certbot-claim0
      - name: certbot-claim1
        persistentVolumeClaim:
          claimName: certbot-claim1
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - certbot
      from:
        kind: ImageStreamTag
        name: certbot:latest
    type: ImageChange
status: {}
