apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  namespace: noaman
spec:
  replicas: 5
  selector:
     matchLabels:
        app: sample-app
  template:
    metadata:
     labels:
        app: sample-app
    spec:
      containers:
         - name: tomcat-container
           image: centos
           ports:
           - containerPort: 8080
  
          
