apiVersion: apps/v1
kind: Deployment
metadata:
   name: sample-deployment
spec:
   replicas: 10
   selector:
     matchLabels:
        app: sample-pod
   template:
     metadata:
       labels:
          app: sample-pod
     spec:
       containers:
       - name: sample-container
         image: tomcat
         ports:
         - containerPort: 8080   
     
