apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  containers:
  - name: sample-container
    image: tomcat
    ports:
    - containerPort: 8080
    volumeMounts:
    - mountPath: /Test
      name: sample-volume
  volumes:
    name: sample-volume
    configmap:
      name: noaman-config
      items:
      - key: hell.properties
        path: imp.conf
