apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sample-pod
  template:
    metadata:
      labels:
        app: sample-pod
    spec:
      containers:
        - name: centos-container
          image: tomcat 
          ports:
          - containerPort: 8080
          command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
