apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
      
    containers:
        - name: tomcat-container
          image: tomcat 
          ports:
          - containerPort: 8080
          command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]

